import os, sys
import ast
import torch
import numpy as np
import pandas as pd
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
from torch.optim.lr_scheduler import ReduceLROnPlateau
from scipy.stats import wilcoxon
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, precision_recall_fscore_support
from sklearn.decomposition import PCA

os.environ["PYTHONHASHSEED"] = str(777)
np.random.seed(777)
torch.manual_seed(777)
torch.use_deterministic_algorithms(True)

# Define test groups to use for testing
test_groups = ["17C", "22N", "25C"]

tw = "4500"
ts = 40
d_strats = ["1", "2", "3", "4"]
k_folds = [str(k) for k in range(10)]
seeds = ["7", "777", "144000"]
epochs = [str(e) for e in range(20)]
date_str = sys.argv[1] # Should be generated by the test_runner.py

# Convert labels to a binary problem
def convert_labels_to_binary(Y_df, b_type):
	if b_type == "More":
		# Merge Slightly class with Not At All class
		Y_df.loc[Y_df["Rating"] == 1, "Rating"] = 0
		Y_df.loc[Y_df["Rating"] > 1, "Rating"] = 1
	
	elif b_type == "Test":
		# Merge Slightly with Very and Extremely class
		Y_df.loc[Y_df["Rating"] >= 1, "Rating"] = 1

	elif b_type == "Less":
		# Remove Slightly class
		Y_df = Y_df[Y_df["Rating"] != 1]
		Y_df.loc[Y_df["Rating"] > 1, "Rating"] = 1
	
	elif b_type == "Balance":
		# Merge Slightly class with Very and Extremely class
		# Then balance the dataframe by removing Slightly instances
		Y_df['Slightly'] = (Y_df['Rating']==1) # Tag Slightly class
		Y_df.loc[Y_df["Rating"] > 1, "Rating"] = 1 # Merge with Very and Extremely
		groups = Y_df['Group'].unique().tolist() # Get development groups
		dev_groups = [g for g in groups if g not in test_groups]
		for i in range(1000):
			curr_group = dev_groups[i % len(dev_groups)] # Cycle through dev groups
			slightly_indices = Y_df[(Y_df['Slightly'])&(Y_df['Group']==curr_group)].index
			if not slightly_indices.empty:
				Y_df = Y_df.drop(slightly_indices[0]) # Drop the Slightly instance
			if len(Y_df[Y_df['Rating']==0]) == len(Y_df[Y_df['Rating']==1]):
				# We have balanced the dataset
				break
	return Y_df

# Define the novel model architecture
class Masked1DCNN(nn.Module):
    """
    1D CNN classifier with modality–time masking.

    Matches Algorithm (activation-level masking):
      - Forward masking: X_tilde = M ⊙ X
      - Gradient freezing: ∇_{X_tilde} ← M ⊙ ∇_{X_tilde}
	  - B = Batch, T = Timesteps, C = Channel features

    Expected dataloader shapes:
      x    : (B, T, C)
      mask : (B, T, C)  with binary entries {0,1}
    Internally converted to (B, C, T) for Conv1d.
    """
    def __init__(self, num_channels, num_timesteps, num_classes, embedding_dim, freeze_input_grads=False):
        super().__init__()
        self.freeze_input_grads = freeze_input_grads

        self.conv1 = nn.Conv1d(in_channels=num_channels, out_channels=32, kernel_size=5, padding=2)
        self.conv2 = nn.Conv1d(in_channels=32, out_channels=64, kernel_size=3, padding=1)
        self.pool = nn.MaxPool1d(kernel_size=2)

        self._to_linear = None
        self._initialize_to_linear(num_channels, num_timesteps)

        self.fc1 = nn.Linear(self._to_linear + embedding_dim, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, num_classes)

    def _initialize_to_linear(self, num_channels, num_timesteps):
        x = torch.rand(1, num_channels, num_timesteps)
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        self._to_linear = x.numel()

    @staticmethod
    def _to_bct(t: torch.Tensor) -> torch.Tensor:
        """Convert (B, T, C) -> (B, C, T)."""
        if t.dim() != 3:
            raise ValueError(f"Expected 3D tensor, got {tuple(t.shape)}")
        return t.permute(0, 2, 1)

    def forward(self, x, mask, embeddings):
        # Forward masking
        x_bct = self._to_bct(x)       # (B, C, T)
        m_bct = self._to_bct(mask)    # (B, C, T)

        # Force input grads so x_masked requires grad
        x_bct = x_bct.detach().requires_grad_(True)

        x_masked = x_bct * m_bct

        if self.freeze_input_grads:
            x_masked.register_hook(lambda g, m=m_bct: g * m)

        x_feat = self.pool(F.relu(self.conv1(x_masked)))
        x_feat = self.pool(F.relu(self.conv2(x_feat)))
        x_feat = x_feat.view(x_feat.size(0), -1)

        combined = torch.cat((x_feat, embeddings), dim=1)
        h = F.relu(self.fc1(combined))
        h = F.relu(self.fc2(h))
        out = self.fc3(h)
        return out

    def register_hooks(self):
        self.freeze_input_grads = True

    def set_mask(self, mask):
        self.mask = mask

# Mirror model parameters
input_size = 12
num_classes = 2
embedding_dim = 155
batch_size = 300
device = torch.device('cpu')

# Directory paths
parent_dir = os.getcwd()
model_dir = "models"
data_dir = "confusion_data"

# Loop through models
final_results = []

# Read in the test data
ada_Y_df = pd.read_csv(os.path.join(parent_dir,data_dir,f"Y_{tw}milli_embedding.tsv"), sep='\t')

# Acquire ChatGPT ada text embeddings
embeddings = np.array([ast.literal_eval(e) for e in ada_Y_df["Embedding"]])

# Applying PCA to reduce the dimensionality
pca = PCA(n_components=embedding_dim)
reduced_embeddings = pca.fit_transform(embeddings)

# Read in sensor data
X_df = pd.read_csv(os.path.join(parent_dir,data_dir,f"X_{tw}milli_{ts}dim_0strat_confusion.tsv"), sep='\t')
Y_df = pd.read_csv(os.path.join(parent_dir,data_dir,f"Y_{tw}milli_{ts}dim_0strat_confusion.tsv"), sep='\t')
XY_df = pd.concat([X_df,Y_df], axis=1)
XY_df = pd.concat([XY_df,ada_Y_df["Embedding"]], axis=1)
XY_df = XY_df[XY_df["Group"].isin(test_groups)]
XY_df = convert_labels_to_binary(XY_df, "Test")

# Convert embeddings to tensor
reduced_embeddings_tensor = torch.tensor(reduced_embeddings[XY_df.index.tolist()], dtype=torch.float32)

# Convert to numpy, selecting the proper columns
select_cols = []
for i in range(1,int(ts)+1):
	for m in [f"m{i}" for i in range(1,input_size+1)]:
		select_cols.append(f"{m}_t{i}")
test_X = XY_df[select_cols].to_numpy()
test_y = XY_df["Rating"].to_numpy()

# Convert to PyTorch tensors
# reshape input for (instances, timesteps, modalities)
inputs_tensor = torch.tensor(test_X.reshape(test_X.shape[0],ts,input_size), dtype=torch.float32)
targets_tensor = torch.tensor(test_y, dtype=torch.long)

# Create DataLoader for test set
test_dataset = TensorDataset(inputs_tensor, reduced_embeddings_tensor, targets_tensor)
test_loader = DataLoader(test_dataset, shuffle=False, num_workers=0, batch_size=batch_size)

for k in k_folds:
	for seed in seeds:
		for epoch in epochs:
			# Define control model
			model_c = Masked1DCNN(input_size, ts, num_classes, embedding_dim)
			model_c.load_state_dict(torch.load(os.path.join(parent_dir,model_dir,f"baseline_model_{tw}tw_{ts}ts_0ds_{k}k_{seed}seed_{epoch}epoch_{date_str}.pth")))
			model_c.to(device)  # Ensure model is on the right device
			model_c.eval()

			for d_s in d_strats:
				# Read in the experiment model
				model_e = Masked1DCNN(input_size, ts, num_classes, embedding_dim)
				model_e.load_state_dict(torch.load(os.path.join(parent_dir,model_dir,f"curr_model_{tw}tw_{ts}ts_{d_s}ds_{k}k_{seed}seed_{epoch}epoch_{date_str}.pth")))
				model_e.to(device)  # Ensure model is on the right device
				model_e.eval()

				all_targets = []
				c_predictions = []
				e_predictions = []
				with torch.no_grad():
					for inputs, batch_embeddings, targets in test_loader:
						# Create instance-specific mask freezing for baseline data
						test_masks = torch.ones_like(inputs)
						for i in range(inputs.size(0)):
							mask = torch.ones(ts, input_size)
							test_masks[i] = mask

						# Move batch over to the GPU
						inputs, batch_embeddings, targets, test_masks = inputs.to(device), batch_embeddings.to(device), targets.to(device), test_masks.to(device)

						outputs_c = model_c(inputs, test_masks, batch_embeddings)
						outputs_e = model_e(inputs, test_masks, batch_embeddings)
						_, predicted_c = torch.max(outputs_c.data, 1)
						_, predicted_e = torch.max(outputs_e.data, 1)
						all_targets.extend(targets.cpu().numpy())
						c_predictions.extend(predicted_c.cpu().numpy())
						e_predictions.extend(predicted_e.cpu().numpy())

				# Collect control metrics
				c_accuracy = accuracy_score(all_targets, c_predictions)
				c_precision = precision_score(all_targets, c_predictions, zero_division=0)
				c_recall = recall_score(all_targets, c_predictions, zero_division=0)
				c_f1 = f1_score(all_targets, c_predictions, zero_division=0)

				# Collect experiment metrics
				e_accuracy = accuracy_score(all_targets, e_predictions)
				e_precision = precision_score(all_targets, e_predictions, zero_division=0)
				e_recall = recall_score(all_targets, e_predictions, zero_division=0)
				e_f1 = f1_score(all_targets, e_predictions, zero_division=0)

				## NEED TO COMPARE TO BEST BASELINE ##
				# So first add baseline results before calculating difference
				if d_s == "1":
					final_results.append({
						"d_s": 0,
						"k": k,
						"seed": seed,
						"epoch": epoch,
						"d_acc": 0,
						"d_prec": 0,
						"d_recall": 0,
						"d_f1": 0,
						"c_acc": f"{c_accuracy:.4f}",
						"c_prec": f"{c_precision:.4f}",
						"c_recall": f"{c_recall:.4f}",
						"c_f1": f"{c_f1:.4f}",
						"e_acc": f"{c_accuracy:.4f}",
						"e_prec": f"{c_precision:.4f}",
						"e_recall": f"{c_recall:.4f}",
						"e_f1": f"{c_f1:.4f}"
					})

				final_results.append({
					"d_s": d_s,
					"k": k,
					"seed": seed,
					"epoch": epoch,
					"d_acc": f"{(e_accuracy-c_accuracy):.4f}",
					"d_prec": f"{(e_precision-c_precision):.4f}",
					"d_recall": f"{(e_recall-c_recall):.4f}",
					"d_f1": f"{(e_f1-c_f1):.4f}",
					"c_acc": f"{c_accuracy:.4f}",
					"c_prec": f"{c_precision:.4f}",
					"c_recall": f"{c_recall:.4f}",
					"c_f1": f"{c_f1:.4f}",
					"e_acc": f"{e_accuracy:.4f}",
					"e_prec": f"{e_precision:.4f}",
					"e_recall": f"{e_recall:.4f}",
					"e_f1": f"{e_f1:.4f}"
				})

# Output results
final_res_df = pd.DataFrame(final_results)
final_res_df.to_csv(os.path.join(parent_dir,"ACII_4500tw_40ts.tsv"), sep='\t', index=False)